const menu = () => {
  const menu = document.createElement('div');
  menu.setAttribute('id', 'menuDiv');
  menu.setAttribute('style', ' display: flex');
  const menuDiv = document.createElement('div');
  menuDiv.setAttribute('id', 'menu');
  menuDiv.setAttribute('style', 'align-text: center');
  menuDiv.innerHTML = '<h1>MENU</h1>';
  const fDiv = document.createElement('div');
  fDiv.classList.add('img');
  fDiv.innerHTML = '<img src="/src/pic/pasta.jpg"> <h3>Mostaccioli is a hearty baked pasta thats perfect for a weeknight dinner.Essentially an easier lasagna made with penne</h3>';
  fDiv.setAttribute('style', 'margin: 2em; display: flex');
  const sDiv = document.createElement('div');
  sDiv.classList.add('img');
  sDiv.innerHTML = '<img src="/src/pic/spizza.jpg"><h3>One of our all time specialties. A meaty feast of double Pepperoni Mozzarella and Tomato sauce.</h3>';
  sDiv.setAttribute('style', 'margin: 2em; display: flex');
  const tDiv = document.createElement('div');
  tDiv.classList.add('img');
  tDiv.innerHTML = '<img src="/src/pic/balls.jpg"><h3>The secret to these homemade beef meatballs is a trifecta of ground beef, ground pork, and Italian sausage </h3>';
  tDiv.setAttribute('style', 'margin: 2em; display: flex');
  const foDiv = document.createElement('div');
  foDiv.classList.add('img');
  foDiv.innerHTML = '<img src="/src/pic/steak.jpg"><h3> Halfway through cooking, these bone-in rib eyes are basted with a mixture of butter, thyme and garlic. </h3>';
  foDiv.setAttribute('style', 'margin: 2em; display: flex');
  menuDiv.appendChild(fDiv);
  menuDiv.appendChild(sDiv);
  menuDiv.appendChild(tDiv);
  menuDiv.appendChild(foDiv);
  const smenuDiv = document.createElement('div');
  smenuDiv.setAttribute('id', 'menu');
  const sfDiv = document.createElement('div');
  sfDiv.classList.add('img');
  sfDiv.innerHTML = '<img src="/src/pic/burger.jpg"> <h3>Burgers & Sandwiches · Closeup of grilled BBQ chicken sandwich with lettuce, tomato and onion on a bun ·</h3>';
  sfDiv.setAttribute('style', 'margin: 2em; display: flex');
  const ssDiv = document.createElement('div');
  ssDiv.classList.add('img');
  ssDiv.innerHTML = '<img src="/src/pic/soup.jpg"><h3>Gordon Ramsays pumpkin soup with wild mushrooms recipe ·</h3>';
  ssDiv.setAttribute('style', 'margin: 2em; display: flex');
  const stDiv = document.createElement('div');
  stDiv.classList.add('img');
  stDiv.innerHTML = '<img src="/src/pic/vsalad.jpg"><h3>V salad</h3>';
  stDiv.setAttribute('style', 'margin: 2em; display: flex');
  const sfoDiv = document.createElement('div');
  sfoDiv.classList.add('img');
  sfoDiv.innerHTML = '<img src="/src/pic/banana.jpg"><h3>A collection of dessert</h3>';
  sfoDiv.setAttribute('style', 'margin: 2em; display: flex');
  smenuDiv.appendChild(sfDiv);
  smenuDiv.appendChild(ssDiv);
  smenuDiv.appendChild(stDiv);
  smenuDiv.appendChild(sfoDiv);
  menu.appendChild(menuDiv);
  menu.appendChild(smenuDiv);
  return menu;
};

export default menu;