import balls from './pic/balls.jpg';
import banana from './pic/banana.jpg';
import burger from './pic/burger.jpg';
import pasta from './pic/pasta.jpg';
import soup from './pic/soup.jpg';
import steak from './pic/steak.jpg';
import pizza from './pic/spizza.jpg';
import salad from './pic/vsalad.jpg';

const menu = () => {
  const menu = document.createElement('div');
  menu.setAttribute('id', 'menuDiv');
  menu.setAttribute('style', ' display: flex');
  const menuDiv = document.createElement('div');
  menuDiv.setAttribute('id', 'menu');
  menuDiv.setAttribute('style', 'align-text: center');
  menuDiv.innerHTML = '<h1>MENU</h1>';
  const fDiv = document.createElement('img');
  fDiv.classList.add('img');
  fDiv.innerHTML = '<h3>Mostaccioli is a hearty baked pasta thats perfect for a weeknight dinner.Essentially an easier lasagna made with penne</h3>';
  fDiv.setAttribute('src', pasta);
  fDiv.setAttribute('style', 'margin: 2em; display: flex');
  const sDiv = document.createElement('img');
  sDiv.classList.add('img');
  sDiv.innerHTML = '<h3>One of our all time specialties. A meaty feast of double Pepperoni Mozzarella and Tomato sauce.</h3>';
  sDiv.setAttribute('src', pizza);
  sDiv.setAttribute('style', 'margin: 2em; display: flex');
  const tDiv = document.createElement('img');
  tDiv.classList.add('img');
  tDiv.innerHTML = '<h3>The secret to these homemade beef meatballs is a trifecta of ground beef, ground pork, and Italian sausage </h3>';
  tDiv.setAttribute('src', balls);
  tDiv.setAttribute('style', 'margin: 2em; display: flex');
  const foDiv = document.createElement('img');
  foDiv.classList.add('img');
  foDiv.innerHTML = '<h3> Halfway through cooking, these bone-in rib eyes are basted with a mixture of butter, thyme and garlic. </h3>';
  foDiv.setAttribute('src', steak);
  foDiv.setAttribute('style', 'margin: 2em; display: flex');
  menuDiv.appendChild(fDiv);
  menuDiv.appendChild(sDiv);
  menuDiv.appendChild(tDiv);
  menuDiv.appendChild(foDiv);
  const smenuDiv = document.createElement('div');
  smenuDiv.setAttribute('id', 'menu');
  const sfDiv = document.createElement('img');
  sfDiv.classList.add('img');
  sfDiv.innerHTML = '<h3>Burgers & Sandwiches · Closeup of grilled BBQ chicken sandwich with lettuce, tomato and onion on a bun ·</h3>';
  sfDiv.setAttribute('src', burger);
  sfDiv.setAttribute('style', 'margin: 2em; display: flex');
  const ssDiv = document.createElement('img');
  ssDiv.classList.add('img');
  ssDiv.innerHTML = '<h3>Gordon Ramsays pumpkin soup with wild mushrooms recipe ·</h3>';
  ssDiv.setAttribute('src', soup);
  ssDiv.setAttribute('style', 'margin: 2em; display: flex');
  const stDiv = document.createElement('img');
  stDiv.classList.add('img');
  stDiv.innerHTML = '<h3>V salad</h3>';
  stDiv.setAttribute('src', salad);
  stDiv.setAttribute('style', 'margin: 2em; display: flex');
  const sfoDiv = document.createElement('img');
  sfoDiv.classList.add('img');
  sfoDiv.innerHTML = '<h3>A collection of dessert</h3>';
  sfoDiv.setAttribute('src', banana);
  sfoDiv.setAttribute('style', 'margin: 2em; display: flex');
  smenuDiv.appendChild(sfDiv);
  smenuDiv.appendChild(ssDiv);
  smenuDiv.appendChild(stDiv);
  smenuDiv.appendChild(sfoDiv);
  menu.appendChild(menuDiv);
  menu.appendChild(smenuDiv);
  return menu;
};

export default menu;